name = "ACEatoms"
uuid = "1e34e032-0b37-4839-a012-196b35408c3c"
authors = ["Christoph Ortner <c.ortner@warwick.ac.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
